### ISSUE TITLE
No requests?

### ISSUE THREAD

**Issue by thanasisk** [fotisl/diavgeia-client#1]
Hi there,
have you considered using the python requests library? It is 2016 ;)

**Comment by fotisl** [comment]
What are the drawbacks of using urlretrieve?

**Comment by thanasisk** [comment]
Personally I would have written it with r = requests.get('whatever') foo.write(r.content), possibly with a check of r.status_code for 200 but I can understand this is a matter of taste. Feel free to close this issue if you feel like it. I would be happy to provide a PR with requests functionality however - just let me know.

**Comment by fotisl** [comment]
I have already made the commit (about 1 minute ago).

**Comment by thanasisk** [comment]
Awesome, cheers!
